### ISSUE TITLE
Multinode support?

### ISSUE THREAD

**Issue by davlaw** [ghostkaa/pxpilot#19]
Something I wish proxmox would incorporate for some time now...

But before I dive in, do you consider multi node operations?  My VMs can sometimes change nodes and I'm not clear myself about how communications between nodes would be handled.   That's where I get stuck mentally.  I have messed with auto-start and delays but its hard to test in a live environment till the next time I have to reboot the "house of cards"?! 

I know this might be clear as mud, but will try to explain more if needed.

**Comment by davlaw** [comment]
Thanks, might just give this a try

**Comment by ghostkaa** [comment]
I'd appreciate any feedback.
